### ISSUE TITLE
module 'busted.runner' not found not found for 0.14.1 and 0.14.0

### ISSUE THREAD

**Issue by krtkvrm** [Kong/kong-pongo#189] opened 2021-08-12 22:13 UTC
I am getting. this error when running pongo, for both Kong 0.14.0 and 0.14.1
```
$ KONG_VERSION=0.14.0 pongo run -v -o gtest ./spec


Kong version: 0.14.0
ERROR: bin/busted:70: module 'busted.runner' not found:No LuaRocks module found for busted.runner
	no field package.preload['busted.runner']
	no file '/usr/local/openresty/site/lualib/busted/runner.ljbc'
	no file '/usr/local/openresty/site/lualib/busted/runner/init.ljbc'
	no file '/usr/local/openresty/lualib/busted/runner.ljbc'
	no file '/usr/local/openresty/lualib/busted/runner/init.ljbc'
	no file '/usr/local/openresty/site/lualib/busted/runner.lua'
	no file '/usr/local/openresty/site/lualib/busted/runner/init.lua'
	no file '/usr/local/openresty/lualib/busted/runner.lua'
	no file '/usr/local/openresty/lualib/busted/runner/init.lua'
	no file '/kong-plugin/busted/runner.lua'
	no file '/kong-plugin/busted/runner/init.lua'
	no file './busted/runner.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/busted/runner.lua'
	no file '/usr/local/share/lua/5.1/busted/runner.lua'
	no file '/usr/local/share/lua/5.1/busted/runner/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/busted/runner.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/busted/runner/init.lua'
	no file '/root/.luarocks/share/lua/5.1/busted/runner.lua'
	no file '/root/.luarocks/share/lua/5.1/busted/runner/init.lua'
	no file '/usr/local/openresty/site/lualib/busted/runner.so'
	no file '/usr/local/openresty/lualib/busted/runner.so'
	no file './busted/runner.so'
	no file '/usr/local/lib/lua/5.1/busted/runner.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/busted/runner.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/busted/runner.so'
	no file '/usr/local/openresty/site/lualib/busted.so'
	no file '/usr/local/openresty/lualib/busted.so'
	no file './busted.so'
	no file '/usr/local/lib/lua/5.1/busted.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/busted.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/busted.so'
stack traceback:
	bin/busted:70: in function 'file_gen'
	init_worker_by_lua:52: in function <init_worker_by_lua:50>
	[C]: in function 'xpcall'
	init_worker_by_lua:59: in function <init_worker_by_lua:57>
make: *** [spec] Error 1
```

**Comment by Tieske** [comment] 2021-08-13 07:32
duplicate of #188

**Comment by Tieske** [comment] 2021-12-20 14:53
typically this is an image build failure, see #241

**Closed by Tieske** 2021-12-20 14:53 UTC
