### ISSUE TITLE
Errors during setup - wsl debian or ubuntu

### ISSUE THREAD

**Issue by chris2016** [Kong/kong-pongo#277] opened 2022-04-14 03:21 UTC
Hi.

I am following the guide to install it but it fails during execution, I tried without root and with root, I am on Windows 11.

Steps I followed for the setup:

```
sudo apt update
sudo apt install git curl coreutils

cd ~
git clone https://github.com/Kong/kong-pongo.git
mkdir -p ~/.local/bin
ln -s $(realpath kong-pongo/pongo.sh) ~/.local/bin/pongo
PATH=$PATH:~/.local/bin

root@chrispc:~/kong-pongo# pongo run
[pongo-INFO] auto-starting the test environment, use the 'pongo down' action to stop it
[+] Running 2/2
 ⠿ Network pongo-1dd560c3               Created                                                                                                                    1.0s
 ⠿ Container pongo-1dd560c3-postgres-1  Started                                                                                                                    1.5s
[+] Running 1/1
 ⠿ Container pongo-1dd560c3-cassandra-1  Started                                                                                                                   1.3s
[pongo-INFO] Waiting for postgres
[pongo-INFO] Waiting for cassandra
[pongo-INFO] image 'kong-pongo-test:2.8.1' not found, auto-building it
[pongo-INFO] starting build of image 'kong-pongo-test:2.8.1'
[+] Building 27.5s (12/13)
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 32B                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/kong:2.8.1-alpine                                                                                               0.0s
 => [1/9] FROM docker.io/library/kong:2.8.1-alpine                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                  0.0s
 => => transferring context: 25.64kB                                                                                                                               0.0s
 => CACHED [2/9] COPY ./kong-versions/2.8.1/kong /kong                                                                                                             0.0s
 => CACHED [3/9] COPY assets/busted_helper.lua      /pongo/busted_helper.lua                                                                                       0.0s
 => CACHED [4/9] COPY assets/pongo_entrypoint.sh    /pongo/pongo_entrypoint.sh                                                                                     0.0s
 => CACHED [5/9] COPY assets/default-pongo-setup.sh /pongo/default-pongo-setup.sh                                                                                  0.0s
 => CACHED [6/9] COPY assets/pongo_pack.lua         /pongo/pongo_pack.lua                                                                                          0.0s
 => CACHED [7/9] COPY assets/pongo_profile.sh       /etc/profile.d/pongo_profile.sh                                                                                0.0s
 => ERROR [8/9] RUN apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl     && curl -k -s -S -L https://github.com  27.4s
[8/9] RUN apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov:
#12 0.641 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
#12 1.275 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
#12 1.709 v3.15.4-23-g26ba280437 [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
#12 1.709 v3.15.4-26-g36f9d42a4c [https://dl-cdn.alpinelinux.org/alpine/v3.15/community]
#12 1.709 OK: 15857 distinct packages available
#12 2.076 (1/51) Installing bsd-compat-headers (0.7.2-r3)
#12 2.223 (2/51) Installing curl (7.80.0-r0)
#12 2.306 (3/51) Installing binutils (2.37-r3)
#12 2.771 (4/51) Installing libgomp (10.3.1_git20211027-r0)
#12 2.849 (5/51) Installing libatomic (10.3.1_git20211027-r0)
#12 2.871 (6/51) Installing libgphobos (10.3.1_git20211027-r0)
#12 3.173 (7/51) Installing gmp (6.2.1-r1)
#12 3.230 (8/51) Installing isl22 (0.22-r0)
#12 3.379 (9/51) Installing mpfr4 (4.1.0-r0)
#12 3.707 (10/51) Installing mpc1 (1.2.1-r0)
#12 3.855 (11/51) Installing gcc (10.3.1_git20211027-r0)
#12 8.712 (12/51) Installing musl-dev (1.2.2-r7)
#12 9.165 (13/51) Installing libc-dev (0.7.2-r3)
#12 9.186 (14/51) Installing g++ (10.3.1_git20211027-r0)
#12 11.79 (15/51) Installing oniguruma (6.9.7.1-r0)
#12 11.92 (16/51) Installing jq (1.6-r1)
#12 11.98 (17/51) Installing m4 (1.4.18-r2)
#12 12.02 (18/51) Installing make (4.3-r0)
#12 12.29 (19/51) Installing openssl-dev (1.1.1n-r0)
#12 12.43 (20/51) Installing libffi (3.4.2-r1)
#12 12.49 (21/51) Installing gdbm (1.22-r0)
#12 12.52 (22/51) Installing xz-libs (5.2.5-r1)
#12 12.59 (23/51) Installing mpdecimal (2.5.1-r1)
#12 12.65 (24/51) Installing sqlite-libs (3.36.0-r0)
#12 12.74 (25/51) Installing python3 (3.9.7-r4)
#12 14.69 (26/51) Installing py3-appdirs (1.4.4-r2)
#12 14.74 (27/51) Installing py3-certifi (2020.12.5-r1)
#12 14.78 (28/51) Installing py3-charset-normalizer (2.0.7-r0)
#12 14.83 (29/51) Installing py3-idna (3.3-r0)
#12 14.87 (30/51) Installing py3-urllib3 (1.26.7-r0)
#12 14.95 (31/51) Installing py3-requests (2.26.0-r1)
#12 15.01 (32/51) Installing py3-msgpack (1.0.2-r1)
#12 15.07 (33/51) Installing py3-lockfile (0.12.2-r4)
#12 15.09 (34/51) Installing py3-cachecontrol (0.12.10-r0)
#12 15.13 (35/51) Installing py3-colorama (0.4.4-r1)
#12 15.18 (36/51) Installing py3-contextlib2 (21.6.0-r1)
#12 15.21 (37/51) Installing py3-distlib (0.3.3-r0)
#12 15.37 (38/51) Installing py3-distro (1.6.0-r0)
#12 15.51 (39/51) Installing py3-six (1.16.0-r0)
#12 15.59 (40/51) Installing py3-webencodings (0.5.1-r4)
#12 15.65 (41/51) Installing py3-html5lib (1.1-r1)
#12 15.72 (42/51) Installing py3-parsing (2.4.7-r2)
#12 15.78 (43/51) Installing py3-packaging (20.9-r1)
#12 15.81 (44/51) Installing py3-tomli (1.2.2-r0)
#12 15.87 (45/51) Installing py3-pep517 (0.12.0-r0)
#12 15.90 (46/51) Installing py3-progress (1.6-r0)
#12 15.92 (47/51) Installing py3-retrying (1.3.3-r2)
#12 15.94 (48/51) Installing py3-ordered-set (4.0.2-r2)
#12 15.97 (49/51) Installing py3-setuptools (52.0.0-r4)
#12 16.09 (50/51) Installing py3-toml (0.10.2-r2)
#12 16.13 (51/51) Installing py3-pip (20.3.4-r1)
#12 16.52 Executing busybox-1.34.1-r5.trigger
#12 16.53 OK: 318 MiB in 91 packages
#12 21.82 curl: (6) Could not resolve host: objects.githubusercontent.com
#12 21.82 tar: invalid magic
#12 21.82 tar: short read
#12 21.84 fatal: not a git repository (or any of the parent directories): .git
#12 27.04 curl: (6) Could not resolve host: objects.githubusercontent.com
#12 27.04 tar: invalid magic
#12 27.04 tar: short read
#12 27.04 make: *** [Makefile:133: bin/grpcurl] Error 1
executor failed running [/bin/sh -c apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov]: exit code: 2
[pongo-ERROR] Error: failed to build test environment
```

Any Idea?

**Comment by Tieske** [comment] 2022-04-14 08:13
from first looks it seems that
```shell
curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin
```
is failing. Could it be a network failure? have you retried?

**Comment by chris2016** [comment] 2022-04-14 10:38
If I issue the command on the shell it downloads the file. There are no network issues. I tried to run pongo on my mac afterwards and it works. There is no proxy.

**Comment by Tieske** [comment] 2022-04-14 12:10
I don't have a win 11 system to test unfortunately. So cannot reproduce.

You can try and debug by modifying the dockerfile, and separating out the failing commands; [file is here](https://github.com/Kong/kong-pongo/blob/master/assets/Dockerfile#L32) might be the curl succeeds, but the untar just fails?

**Comment by Tieske** [comment] 2022-05-13 14:34
@chris2016 did you manage to figure this one out?

**Comment by Tieske** [comment] 2022-07-06 15:02
closing this

**Closed by Tieske** 2022-07-06 15:02 UTC
